// World Cup Simulator - Complete Historical Teams Data
// Includes teams from all World Cups (1930-2022)

const WORLD_CUP_DATA = {
  year: 2022,
  country: 'Qatar',
  allTeams: {
    // 2022 Copa do Mundo
    'Argentina': {
      code: 'ARG',
      flag: '🇦🇷',
      players: [
        { number: 1, name: 'Emiliano Martínez', position: 'GR', rating: 85 },
        { number: 2, name: 'Gonzalo Montiel', position: 'D', rating: 78 },
        { number: 3, name: 'Nicolás Otamendi', position: 'D', rating: 82 },
        { number: 4, name: 'Lisandro Martínez', position: 'D', rating: 80 },
        { number: 5, name: 'Juan Foyth', position: 'D', rating: 76 },
        { number: 6, name: 'Germán Pezzella', position: 'D', rating: 77 },
        { number: 7, name: 'Alejandro Garnacho', position: 'A', rating: 75 },
        { number: 8, name: 'Enzo Fernández', position: 'M', rating: 81 },
        { number: 9, name: 'Julián Álvarez', position: 'A', rating: 83 },
        { number: 10, name: 'Lionel Messi', position: 'A', rating: 93 },
        { number: 11, name: 'Ángel Di María', position: 'A', rating: 84 },
        { number: 12, name: 'Franco Armani', position: 'GR', rating: 78 },
        { number: 13, name: 'Cristian Romero', position: 'D', rating: 81 },
        { number: 14, name: 'Leandro Paredes', position: 'M', rating: 79 },
        { number: 15, name: 'Guido Rodríguez', position: 'M', rating: 77 },
        { number: 16, name: 'Alexis Mac Allister', position: 'M', rating: 80 },
        { number: 17, name: 'Gonzalo Higuaín', position: 'A', rating: 76 },
        { number: 18, name: 'Joaquín Correa', position: 'A', rating: 77 },
        { number: 19, name: 'Sergio Agüero', position: 'A', rating: 74 },
        { number: 20, name: 'Gio Lo Celso', position: 'M', rating: 78 },
        { number: 21, name: 'Exequiel Palacios', position: 'M', rating: 76 },
        { number: 22, name: 'Juan Musso', position: 'GR', rating: 79 },
        { number: 23, name: 'Marcos Acuña', position: 'D', rating: 79 },
        { number: 24, name: 'Nahuel Molina', position: 'D', rating: 80 },
        { number: 25, name: 'Mateo Retegui', position: 'A', rating: 72 },
        { number: 26, name: 'Thiago Almada', position: 'M', rating: 77 }
      ]
    },
    'Brasil': {
      code: 'BRA',
      flag: '🇧🇷',
      players: [
        { number: 1, name: 'Alisson', position: 'GR', rating: 89 },
        { number: 2, name: 'Danilo', position: 'D', rating: 80 },
        { number: 3, name: 'Thiago Silva', position: 'D', rating: 85 },
        { number: 4, name: 'Éder Militão', position: 'D', rating: 82 },
        { number: 5, name: 'Alex Sandro', position: 'D', rating: 80 },
        { number: 6, name: 'Bremer', position: 'D', rating: 81 },
        { number: 7, name: 'Lucas Paquetá', position: 'M', rating: 79 },
        { number: 8, name: 'Casemiro', position: 'M', rating: 88 },
        { number: 9, name: 'Gabriel Jesus', position: 'A', rating: 82 },
        { number: 10, name: 'Neymar', position: 'A', rating: 91 },
        { number: 11, name: 'Vinícius Júnior', position: 'A', rating: 86 },
        { number: 12, name: 'Ederson', position: 'GR', rating: 84 },
        { number: 13, name: 'Marquinhos', position: 'D', rating: 84 },
        { number: 14, name: 'Fred', position: 'M', rating: 77 },
        { number: 15, name: 'Bruno Guimarães', position: 'M', rating: 81 },
        { number: 16, name: 'Fabinho', position: 'M', rating: 79 },
        { number: 17, name: 'Antony', position: 'A', rating: 80 },
        { number: 18, name: 'Rodrygo', position: 'A', rating: 82 },
        { number: 19, name: 'Richarlison', position: 'A', rating: 81 },
        { number: 20, name: 'Vinicius', position: 'A', rating: 76 },
        { number: 21, name: 'Éverton Ribeiro', position: 'M', rating: 76 },
        { number: 22, name: 'Weverton', position: 'GR', rating: 80 },
        { number: 23, name: 'Renan Lodi', position: 'D', rating: 77 },
        { number: 24, name: 'Emerson Royal', position: 'D', rating: 78 },
        { number: 25, name: 'Matheus Cunha', position: 'A', rating: 76 },
        { number: 26, name: 'Fabio Santos', position: 'D', rating: 72 }
      ]
    },
    'França': {
      code: 'FRA',
      flag: '🇫🇷',
      players: [
        { number: 1, name: 'Hugo Lloris', position: 'GR', rating: 86 },
        { number: 2, name: 'Achraf Hakimi', position: 'D', rating: 83 },
        { number: 3, name: 'Dayot Upamecano', position: 'D', rating: 81 },
        { number: 4, name: 'Raphaël Varane', position: 'D', rating: 84 },
        { number: 5, name: 'Jules Koundé', position: 'D', rating: 82 },
        { number: 6, name: 'Benjamin Pavard', position: 'D', rating: 80 },
        { number: 7, name: 'Antoine Griezmann', position: 'M', rating: 86 },
        { number: 8, name: 'Aurélien Tchouaméni', position: 'M', rating: 80 },
        { number: 9, name: 'Olivier Giroud', position: 'A', rating: 81 },
        { number: 10, name: 'Kylian Mbappé', position: 'A', rating: 94 },
        { number: 11, name: 'Ousmane Dembélé', position: 'A', rating: 84 },
        { number: 12, name: 'Steve Mandanda', position: 'GR', rating: 79 },
        { number: 13, name: 'William Saliba', position: 'D', rating: 79 },
        { number: 14, name: 'Adrien Rabiot', position: 'M', rating: 80 },
        { number: 15, name: 'Matteo Guendouzi', position: 'M', rating: 77 },
        { number: 16, name: 'Youssouf Fofana', position: 'M', rating: 78 },
        { number: 17, name: 'Kingsley Coman', position: 'A', rating: 83 },
        { number: 18, name: 'Théo Hernández', position: 'D', rating: 81 },
        { number: 19, name: 'Presnel Kimpembe', position: 'D', rating: 79 },
        { number: 20, name: 'Eduardo Camavinga', position: 'M', rating: 79 },
        { number: 21, name: 'Moussa Diaby', position: 'A', rating: 81 },
        { number: 22, name: 'Alphonse Areola', position: 'GR', rating: 78 },
        { number: 23, name: 'Lucas Hernández', position: 'D', rating: 80 },
        { number: 24, name: 'Jonathan Clauss', position: 'D', rating: 76 },
        { number: 25, name: 'Randal Kolo Muani', position: 'A', rating: 76 },
        { number: 26, name: 'Axel Disasi', position: 'D', rating: 75 }
      ]
    },
    'Alemanha': {
      code: 'GER',
      flag: '🇩🇪',
      players: [
        { number: 1, name: 'Manuel Neuer', position: 'GR', rating: 87 },
        { number: 2, name: 'Thilo Kehrer', position: 'D', rating: 78 },
        { number: 3, name: 'Antonio Rüdiger', position: 'D', rating: 83 },
        { number: 4, name: 'Matthias Ginter', position: 'D', rating: 79 },
        { number: 5, name: 'David Raum', position: 'D', rating: 77 },
        { number: 6, name: 'Jérôme Boateng', position: 'D', rating: 76 },
        { number: 7, name: 'Kai Havertz', position: 'M', rating: 83 },
        { number: 8, name: 'Ilkay Gündoğan', position: 'M', rating: 82 },
        { number: 9, name: 'Serge Gnabry', position: 'A', rating: 81 },
        { number: 10, name: 'Leroy Sané', position: 'A', rating: 84 },
        { number: 11, name: 'Thomas Müller', position: 'A', rating: 82 },
        { number: 12, name: 'Marc-André ter Stegen', position: 'GR', rating: 85 },
        { number: 13, name: 'Mats Hummels', position: 'D', rating: 80 },
        { number: 14, name: 'Emre Can', position: 'M', rating: 77 },
        { number: 15, name: 'Julian Draxler', position: 'M', rating: 78 },
        { number: 16, name: 'Florian Wirtz', position: 'M', rating: 81 },
        { number: 17, name: 'Niclas Füllkrug', position: 'A', rating: 76 },
        { number: 18, name: 'Jamal Musiala', position: 'M', rating: 85 },
        { number: 19, name: 'Christoph Baumgartner', position: 'M', rating: 75 },
        { number: 20, name: 'Robin Gosens', position: 'D', rating: 77 },
        { number: 21, name: 'Lukas Nmecha', position: 'M', rating: 74 },
        { number: 22, name: 'Bernd Leno', position: 'GR', rating: 80 },
        { number: 23, name: 'Armel Bella-Kotchap', position: 'D', rating: 74 },
        { number: 24, name: 'Christian Günter', position: 'D', rating: 76 },
        { number: 25, name: 'Youssoufa Moukoko', position: 'A', rating: 75 },
        { number: 26, name: 'Salih Özcan', position: 'M', rating: 75 }
      ]
    },
    'Espanha': {
      code: 'ESP',
      flag: '🇪🇸',
      players: [
        { number: 1, name: 'Unai Simón', position: 'GR', rating: 80 },
        { number: 2, name: 'Jesús Navas', position: 'D', rating: 79 },
        { number: 3, name: 'Sergio Busquets', position: 'M', rating: 82 },
        { number: 4, name: 'Pau Torres', position: 'D', rating: 80 },
        { number: 5, name: 'Gavi', position: 'M', rating: 83 },
        { number: 6, name: 'Pedri', position: 'M', rating: 84 },
        { number: 7, name: 'Álvaro Morata', position: 'A', rating: 81 },
        { number: 8, name: 'Koke', position: 'M', rating: 80 },
        { number: 9, name: 'Ferran Torres', position: 'A', rating: 81 },
        { number: 10, name: 'Nico Williams', position: 'A', rating: 82 },
        { number: 11, name: 'Ansu Fati', position: 'A', rating: 79 },
        { number: 12, name: 'Robert Sánchez', position: 'GR', rating: 77 },
        { number: 13, name: 'César Azpilicueta', position: 'D', rating: 78 },
        { number: 14, name: 'Jordi Alba', position: 'D', rating: 79 },
        { number: 15, name: 'Eric García', position: 'D', rating: 76 },
        { number: 16, name: 'Rodri', position: 'M', rating: 86 },
        { number: 17, name: 'Marcos Llorente', position: 'M', rating: 79 },
        { number: 18, name: 'Alejandro Balde', position: 'D', rating: 75 },
        { number: 19, name: 'Iñigo Martínez', position: 'D', rating: 77 },
        { number: 20, name: 'Dani Olmo', position: 'M', rating: 80 },
        { number: 21, name: 'Yeremy Pino', position: 'A', rating: 76 },
        { number: 22, name: 'Kepa Arrizabalaga', position: 'GR', rating: 76 },
        { number: 23, name: 'Alejandro Garnacho', position: 'A', rating: 75 },
        { number: 24, name: 'Sergi Roberto', position: 'D', rating: 75 },
        { number: 25, name: 'Raúl de Tomás', position: 'A', rating: 74 },
        { number: 26, name: 'Pablo Fornals', position: 'M', rating: 76 }
      ]
    },
    'Inglaterra': {
      code: 'ENG',
      flag: '🇬🇧',
      players: [
        { number: 1, name: 'Jordan Pickford', position: 'GR', rating: 82 },
        { number: 2, name: 'Kyle Walker', position: 'D', rating: 83 },
        { number: 3, name: 'Harry Maguire', position: 'D', rating: 79 },
        { number: 4, name: 'John Stones', position: 'D', rating: 81 },
        { number: 5, name: 'Luke Shaw', position: 'D', rating: 79 },
        { number: 6, name: 'Ben White', position: 'D', rating: 80 },
        { number: 7, name: 'Mason Mount', position: 'M', rating: 81 },
        { number: 8, name: 'Jude Bellingham', position: 'M', rating: 84 },
        { number: 9, name: 'Harry Kane', position: 'A', rating: 89 },
        { number: 10, name: 'Raheem Sterling', position: 'A', rating: 84 },
        { number: 11, name: 'Bukayo Saka', position: 'A', rating: 83 },
        { number: 12, name: 'Aaron Ramsdale', position: 'GR', rating: 79 },
        { number: 13, name: 'Conor Coady', position: 'D', rating: 76 },
        { number: 14, name: 'James Maddison', position: 'M', rating: 80 },
        { number: 15, name: 'Declan Rice', position: 'M', rating: 82 },
        { number: 16, name: 'Jordan Henderson', position: 'M', rating: 79 },
        { number: 17, name: 'Phil Foden', position: 'M', rating: 86 },
        { number: 18, name: 'Kieran Trippier', position: 'D', rating: 78 },
        { number: 19, name: 'Reece James', position: 'D', rating: 81 },
        { number: 20, name: 'Marcus Rashford', position: 'A', rating: 84 },
        { number: 21, name: 'Callum Wilson', position: 'A', rating: 78 },
        { number: 22, name: 'Nick Pope', position: 'GR', rating: 80 },
        { number: 23, name: 'Tyrone Mings', position: 'D', rating: 76 },
        { number: 24, name: 'Kalvin Phillips', position: 'M', rating: 75 },
        { number: 25, name: 'Jarrod Bowen', position: 'A', rating: 79 },
        { number: 26, name: 'Ivan Perišić', position: 'D', rating: 77 }
      ]
    },
    'Holanda': {
      code: 'NED',
      flag: '🇳🇱',
      players: [
        { number: 1, name: 'Remko Pasveer', position: 'GR', rating: 77 },
        { number: 2, name: 'Jurriën Timber', position: 'D', rating: 79 },
        { number: 3, name: 'Matthijs de Ligt', position: 'D', rating: 82 },
        { number: 4, name: 'Virgil van Dijk', position: 'D', rating: 88 },
        { number: 5, name: 'Nathan Aké', position: 'D', rating: 80 },
        { number: 6, name: 'Stefan de Vrij', position: 'D', rating: 81 },
        { number: 7, name: 'Steven Bergwijn', position: 'A', rating: 79 },
        { number: 8, name: 'Cody Gakpo', position: 'A', rating: 82 },
        { number: 9, name: 'Luuk de Jong', position: 'A', rating: 78 },
        { number: 10, name: 'Memphis Depay', position: 'A', rating: 83 },
        { number: 11, name: 'Steven Berghuis', position: 'M', rating: 78 },
        { number: 12, name: 'Justin Bijlow', position: 'GR', rating: 76 },
        { number: 13, name: 'Davy Klaassen', position: 'M', rating: 77 },
        { number: 14, name: 'Marten de Roon', position: 'M', rating: 76 },
        { number: 15, name: 'Tyrell Malacia', position: 'D', rating: 76 },
        { number: 16, name: 'Daley Blind', position: 'D', rating: 77 },
        { number: 17, name: 'Vincent Janssen', position: 'A', rating: 75 },
        { number: 18, name: 'Wout Weghorst', position: 'A', rating: 77 },
        { number: 19, name: 'Teun Koopmeiners', position: 'M', rating: 78 },
        { number: 20, name: 'Frenkie de Jong', position: 'M', rating: 85 },
        { number: 21, name: 'Denzel Dumfries', position: 'D', rating: 80 },
        { number: 22, name: 'Andries Noppert', position: 'GR', rating: 74 },
        { number: 23, name: 'Kenneth Taylor', position: 'M', rating: 74 },
        { number: 24, name: 'Xavi Simons', position: 'M', rating: 76 },
        { number: 25, name: 'Jeremie Frimpong', position: 'D', rating: 78 },
        { number: 26, name: 'Noa Lang', position: 'A', rating: 76 }
      ]
    },
    'Portugal': {
      code: 'POR',
      flag: '🇵🇹',
      players: [
        { number: 1, name: 'Rui Patrício', position: 'GR', rating: 82 },
        { number: 2, name: 'Diogo Dalot', position: 'D', rating: 80 },
        { number: 3, name: 'Pepe', position: 'D', rating: 81 },
        { number: 4, name: 'Rúben Dias', position: 'D', rating: 84 },
        { number: 5, name: 'Nélson Semedo', position: 'D', rating: 80 },
        { number: 6, name: 'João Cancelo', position: 'D', rating: 85 },
        { number: 7, name: 'Bruno Fernandes', position: 'M', rating: 88 },
        { number: 8, name: 'Rúben Neves', position: 'M', rating: 80 },
        { number: 9, name: 'Gonçalo Guedes', position: 'A', rating: 79 },
        { number: 10, name: 'Cristiano Ronaldo', position: 'A', rating: 89 },
        { number: 11, name: 'João Félix', position: 'A', rating: 84 },
        { number: 12, name: 'José Sá', position: 'GR', rating: 80 },
        { number: 13, name: 'Nuno Mendes', position: 'D', rating: 81 },
        { number: 14, name: 'Mário Rui', position: 'D', rating: 76 },
        { number: 15, name: 'Otávio', position: 'M', rating: 80 },
        { number: 16, name: 'Matheus Nunes', position: 'M', rating: 79 },
        { number: 17, name: 'Bernardo Silva', position: 'M', rating: 84 },
        { number: 18, name: 'Rafael Leão', position: 'A', rating: 84 },
        { number: 19, name: 'Diogo Jota', position: 'A', rating: 82 },
        { number: 20, name: 'Trincão', position: 'A', rating: 77 },
        { number: 21, name: 'Pauleta', position: 'A', rating: 74 },
        { number: 22, name: 'Lopes', position: 'GR', rating: 76 },
        { number: 23, name: 'Tiago Djaló', position: 'D', rating: 75 },
        { number: 24, name: 'Inácio', position: 'D', rating: 78 },
        { number: 25, name: 'Bruma', position: 'M', rating: 76 },
        { number: 26, name: 'Vitinha', position: 'M', rating: 80 }
      ]
    },
    'Uruguai': {
      code: 'URU',
      flag: '🇺🇾',
      players: [
        { number: 1, name: 'Sergio Rochet', position: 'GR', rating: 77 },
        { number: 2, name: 'Martín Cáceres', position: 'D', rating: 79 },
        { number: 3, name: 'José María Giménez', position: 'D', rating: 81 },
        { number: 4, name: 'Diego Godín', position: 'D', rating: 80 },
        { number: 5, name: 'Guillermo Varela', position: 'D', rating: 77 },
        { number: 6, name: 'Matías Viña', position: 'D', rating: 78 },
        { number: 7, name: 'Giorgian de Arrascaeta', position: 'M', rating: 81 },
        { number: 8, name: 'Federico Valverde', position: 'M', rating: 84 },
        { number: 9, name: 'Edinson Cavani', position: 'A', rating: 83 },
        { number: 10, name: 'Luis Suárez', position: 'A', rating: 85 },
        { number: 11, name: 'Nicolás De La Cruz', position: 'M', rating: 79 },
        { number: 12, name: 'Fernando Muslera', position: 'GR', rating: 79 },
        { number: 13, name: 'Sebastián Coates', position: 'D', rating: 78 },
        { number: 14, name: 'Lucas Torreira', position: 'M', rating: 78 },
        { number: 15, name: 'Manuel Ugarte', position: 'M', rating: 79 },
        { number: 16, name: 'Rodrigo Bentancur', position: 'M', rating: 80 },
        { number: 17, name: 'Darwin Núñez', position: 'A', rating: 85 },
        { number: 18, name: 'Facundo Pellistri', position: 'A', rating: 76 },
        { number: 19, name: 'Cristhian Stuani', position: 'A', rating: 76 },
        { number: 20, name: 'Agustín Canobbio', position: 'A', rating: 75 },
        { number: 21, name: 'Gaston Pereiro', position: 'M', rating: 75 },
        { number: 22, name: 'Campana', position: 'GR', rating: 74 },
        { number: 23, name: 'Nández', position: 'M', rating: 76 },
        { number: 24, name: 'Olivera', position: 'D', rating: 74 },
        { number: 25, name: 'Lodeiro', position: 'M', rating: 77 },
        { number: 26, name: 'Maxi Gómez', position: 'A', rating: 74 }
      ]
    },
    'Bélgica': {
      code: 'BEL',
      flag: '🇧🇪',
      players: [
        { number: 1, name: 'Thibaut Courtois', position: 'GR', rating: 88 },
        { number: 2, name: 'Toby Alderweireld', position: 'D', rating: 80 },
        { number: 3, name: 'Jan Vertonghen', position: 'D', rating: 79 },
        { number: 4, name: 'Dedryck Boyata', position: 'D', rating: 77 },
        { number: 5, name: 'Thomas Meunier', position: 'D', rating: 79 },
        { number: 6, name: 'Axel Witsel', position: 'M', rating: 80 },
        { number: 7, name: 'Kevin De Bruyne', position: 'M', rating: 91 },
        { number: 8, name: 'Youri Tielemans', position: 'M', rating: 81 },
        { number: 9, name: 'Romelu Lukaku', position: 'A', rating: 85 },
        { number: 10, name: 'Eden Hazard', position: 'A', rating: 86 },
        { number: 11, name: 'Thorgan Hazard', position: 'A', rating: 80 },
        { number: 12, name: 'Simon Mignolet', position: 'GR', rating: 78 },
        { number: 13, name: 'Sander Berge', position: 'M', rating: 77 },
        { number: 14, name: 'Leander Dendoncker', position: 'D', rating: 76 },
        { number: 15, name: 'Jérôme Onguéné', position: 'D', rating: 75 },
        { number: 16, name: 'Wout Faes', position: 'D', rating: 77 },
        { number: 17, name: 'Yannick Carrasco', position: 'A', rating: 80 },
        { number: 18, name: 'Dries Mertens', position: 'A', rating: 79 },
        { number: 19, name: 'Michy Batshuayi', position: 'A', rating: 77 },
        { number: 20, name: 'Jérémy Doku', position: 'A', rating: 81 },
        { number: 21, name: 'Alexis Saelemaekers', position: 'A', rating: 76 },
        { number: 22, name: 'Koen Casteels', position: 'GR', rating: 76 },
        { number: 23, name: 'Zeno Debast', position: 'D', rating: 74 },
        { number: 24, name: 'Konrad de la Fuente', position: 'A', rating: 73 },
        { number: 25, name: 'Dante Vanzeir', position: 'A', rating: 72 },
        { number: 26, name: 'Conor Coady', position: 'D', rating: 76 }
      ]
    },
    'Croácia': {
      code: 'CRO',
      flag: '🇭🇷',
      players: [
        { number: 1, name: 'Dominik Livaković', position: 'GR', rating: 83 },
        { number: 2, name: 'Šime Vrsaljko', position: 'D', rating: 77 },
        { number: 3, name: 'Dejan Lovren', position: 'D', rating: 79 },
        { number: 4, name: 'Joško Gvardiol', position: 'D', rating: 82 },
        { number: 5, name: 'Borna Barišić', position: 'D', rating: 78 },
        { number: 6, name: 'Marcelo Brozović', position: 'M', rating: 83 },
        { number: 7, name: 'Luka Modrić', position: 'M', rating: 87 },
        { number: 8, name: 'Mateo Kovačić', position: 'M', rating: 84 },
        { number: 9, name: 'Andrej Kramarić', position: 'A', rating: 81 },
        { number: 10, name: 'Luka Ivanišević', position: 'A', rating: 79 },
        { number: 11, name: 'Ivan Perišić', position: 'A', rating: 82 },
        { number: 12, name: 'Ivo Grbić', position: 'GR', rating: 76 },
        { number: 13, name: 'Dani Olmo', position: 'M', rating: 80 },
        { number: 14, name: 'Nikola Vlašić', position: 'M', rating: 79 },
        { number: 15, name: 'Kristijan Jakić', position: 'M', rating: 77 },
        { number: 16, name: 'Lovro Majer', position: 'M', rating: 78 },
        { number: 17, name: 'Marko Livaja', position: 'A', rating: 76 },
        { number: 18, name: 'Bruno Petković', position: 'A', rating: 78 },
        { number: 19, name: 'Mislav Oršić', position: 'A', rating: 77 },
        { number: 20, name: 'Ante Budimir', position: 'A', rating: 76 },
        { number: 21, name: 'Sime Žarko', position: 'D', rating: 74 },
        { number: 22, name: 'Nediljko Labrović', position: 'GR', rating: 74 },
        { number: 23, name: 'Roko Jurčević', position: 'D', rating: 73 },
        { number: 24, name: 'Petar Musa', position: 'A', rating: 74 },
        { number: 25, name: 'Josip Juranović', position: 'D', rating: 77 },
        { number: 26, name: 'Marko Milinović', position: 'M', rating: 72 }
      ]
    },
    'Marrocos': {
      code: 'MAR',
      flag: '🇲🇦',
      players: [
        { number: 1, name: 'Bono', position: 'GR', rating: 81 },
        { number: 2, name: 'Achraf Hakimi', position: 'D', rating: 84 },
        { number: 3, name: 'Romain Saïss', position: 'D', rating: 78 },
        { number: 4, name: 'Nayef Aguerd', position: 'D', rating: 79 },
        { number: 5, name: 'Achraf Dari', position: 'D', rating: 77 },
        { number: 6, name: 'Noussair Mazraoui', position: 'D', rating: 81 },
        { number: 7, name: 'Sofyan Amrabat', position: 'M', rating: 84 },
        { number: 8, name: 'Selim Bentaleb', position: 'M', rating: 78 },
        { number: 9, name: 'Hakim Ziyech', position: 'M', rating: 82 },
        { number: 10, name: 'Youssef En-Nesyri', position: 'A', rating: 81 },
        { number: 11, name: 'Sofiane Boufal', position: 'A', rating: 80 },
        { number: 12, name: 'Munir', position: 'GR', rating: 77 },
        { number: 13, name: 'Yahya Attiyat Allah', position: 'D', rating: 75 },
        { number: 14, name: 'Bilal El Khannouss', position: 'M', rating: 76 },
        { number: 15, name: 'Azzedine Ounahi', position: 'M', rating: 79 },
        { number: 16, name: 'Badr Benoun', position: 'M', rating: 74 },
        { number: 17, name: 'Zakaria Aboukhlal', position: 'A', rating: 76 },
        { number: 18, name: 'Abdelhamid Sabiri', position: 'M', rating: 77 },
        { number: 19, name: 'Walid Cheddira', position: 'A', rating: 75 },
        { number: 20, name: 'Anass Zaroury', position: 'A', rating: 77 },
        { number: 21, name: 'Ilias Chair', position: 'M', rating: 76 },
        { number: 22, name: 'Ahmed Reda Tagnaouti', position: 'GR', rating: 73 },
        { number: 23, name: 'Romain Saïss', position: 'D', rating: 76 },
        { number: 24, name: 'Yahya Attiyat Allah', position: 'D', rating: 75 },
        { number: 25, name: 'Tarik Tissoudali', position: 'A', rating: 74 },
        { number: 26, name: 'Abdelhamid Sabiri', position: 'M', rating: 77 }
      ]
    },
    'Polônia': {
      code: 'POL',
      flag: '🇵🇱',
      players: [
        { number: 1, name: 'Wojciech Szczęsny', position: 'GR', rating: 84 },
        { number: 2, name: 'Bartosz Bereszyński', position: 'D', rating: 79 },
        { number: 3, name: 'Jan Bednarek', position: 'D', rating: 78 },
        { number: 4, name: 'Kamil Glik', position: 'D', rating: 77 },
        { number: 5, name: 'Łukasz Fabiański', position: 'D', rating: 76 },
        { number: 6, name: 'Mateusz Wieteska', position: 'D', rating: 75 },
        { number: 7, name: 'Piotr Zieliński', position: 'M', rating: 82 },
        { number: 8, name: 'Jakub Moder', position: 'M', rating: 78 },
        { number: 9, name: 'Arkadiusz Milik', position: 'A', rating: 81 },
        { number: 10, name: 'Robert Lewandowski', position: 'A', rating: 92 },
        { number: 11, name: 'Kamil Jóźwiak', position: 'A', rating: 76 },
        { number: 12, name: 'Łukasz Skorupski', position: 'GR', rating: 78 },
        { number: 13, name: 'Matty Cash', position: 'D', rating: 77 },
        { number: 14, name: 'Krystian Bielik', position: 'M', rating: 76 },
        { number: 15, name: 'Damian Szymański', position: 'D', rating: 74 },
        { number: 16, name: 'Grzegorz Krychowiak', position: 'M', rating: 76 },
        { number: 17, name: 'Karol Świderski', position: 'A', rating: 76 },
        { number: 18, name: 'Szymon Żurkowski', position: 'M', rating: 75 },
        { number: 19, name: 'Nicola Zalewski', position: 'D', rating: 75 },
        { number: 20, name: 'Bartosz Salamon', position: 'D', rating: 73 },
        { number: 21, name: 'Rafał Gikiewicz', position: 'GR', rating: 75 },
        { number: 22, name: 'Radosław Majecki', position: 'GR', rating: 74 },
        { number: 23, name: 'Tymoteusz Puchacz', position: 'D', rating: 72 },
        { number: 24, name: 'Tomás Esteves', position: 'D', rating: 71 },
        { number: 25, name: 'Maciej Rybus', position: 'D', rating: 74 },
        { number: 26, name: 'Paweł Dawidowski', position: 'M', rating: 70 }
      ]
    },
    'Japão': {
      code: 'JPN',
      flag: '🇯🇵',
      players: [
        { number: 1, name: 'Shuichi Gonda', position: 'GR', rating: 77 },
        { number: 2, name: 'Hiroki Sakai', position: 'D', rating: 76 },
        { number: 3, name: 'Yuto Nagatomo', position: 'D', rating: 75 },
        { number: 4, name: 'Mats Sels', position: 'D', rating: 74 },
        { number: 5, name: 'Shoji Tomiyoshi', position: 'D', rating: 75 },
        { number: 6, name: 'Riku Yamane', position: 'D', rating: 74 },
        { number: 7, name: 'Takumi Minamino', position: 'M', rating: 79 },
        { number: 8, name: 'Gaku Shibasaki', position: 'M', rating: 77 },
        { number: 9, name: 'Ao Tanaka', position: 'M', rating: 76 },
        { number: 10, name: 'Shinji Okazaki', position: 'A', rating: 76 },
        { number: 11, name: 'Kaoru Mitoma', position: 'A', rating: 78 },
        { number: 12, name: 'Eiji Kawashima', position: 'GR', rating: 76 },
        { number: 13, name: 'Hirving Lozano', position: 'A', rating: 80 },
        { number: 14, name: 'Wataru Endo', position: 'M', rating: 76 },
        { number: 15, name: 'Yuki Soma', position: 'D', rating: 73 },
        { number: 16, name: 'Yukinari Sugawara', position: 'D', rating: 74 },
        { number: 17, name: 'Ritsu Doan', position: 'M', rating: 78 },
        { number: 18, name: 'Daichi Kamada', position: 'M', rating: 77 },
        { number: 19, name: 'Daizen Maeda', position: 'A', rating: 76 },
        { number: 20, name: 'Hiruma Yoshida', position: 'D', rating: 72 },
        { number: 21, name: 'Ryo Miyaichi', position: 'A', rating: 74 },
        { number: 22, name: 'Kosuke Nakamura', position: 'GR', rating: 73 },
        { number: 23, name: 'Yohei Ito', position: 'D', rating: 72 },
        { number: 24, name: 'Takehiro Tomiyasu', position: 'D', rating: 77 },
        { number: 25, name: 'Hiroki Ito', position: 'D', rating: 75 },
        { number: 26, name: 'Junya Ito', position: 'A', rating: 75 }
      ]
    },
    'México': {
      code: 'MEX',
      flag: '🇲🇽',
      players: [
        { number: 1, name: 'Guillermo Ochoa', position: 'GR', rating: 80 },
        { number: 2, name: 'Jorge Sánchez', position: 'D', rating: 76 },
        { number: 3, name: 'Héctor Moreno', position: 'D', rating: 77 },
        { number: 4, name: 'Carlos Salcedo', position: 'D', rating: 75 },
        { number: 5, name: 'Jesús Gallardo', position: 'D', rating: 76 },
        { number: 6, name: 'Edson Álvarez', position: 'M', rating: 80 },
        { number: 7, name: 'Andrés Guardado', position: 'M', rating: 77 },
        { number: 8, name: 'Erick Gutiérrez', position: 'M', rating: 76 },
        { number: 9, name: 'Raúl Jiménez', position: 'A', rating: 80 },
        { number: 10, name: 'Hirving Lozano', position: 'A', rating: 82 },
        { number: 11, name: 'Alexis Vega', position: 'A', rating: 77 },
        { number: 12, name: 'Alfredo Talavera', position: 'GR', rating: 77 },
        { number: 13, name: 'Néstor Araujo', position: 'D', rating: 75 },
        { number: 14, name: 'Orbelin Pineda', position: 'M', rating: 76 },
        { number: 15, name: 'Rodolfo Pizarro', position: 'M', rating: 75 },
        { number: 16, name: 'Luis Romo', position: 'M', rating: 74 },
        { number: 17, name: 'Uriel Antuna', position: 'A', rating: 75 },
        { number: 18, name: 'Rogelio Funes Mori', position: 'A', rating: 76 },
        { number: 19, name: 'Santiago Giménez', position: 'A', rating: 77 },
        { number: 20, name: 'Efraín Álvarez', position: 'D', rating: 73 },
        { number: 21, name: 'Gerardo Arteaga', position: 'D', rating: 74 },
        { number: 22, name: 'Luis Malagón', position: 'GR', rating: 75 },
        { number: 23, name: 'Julio Domínguez', position: 'D', rating: 72 },
        { number: 24, name: 'Gilberto Sepúlveda', position: 'D', rating: 71 },
        { number: 25, name: 'Javier López', position: 'M', rating: 72 },
        { number: 26, name: 'Jesús Corona', position: 'M', rating: 75 }
      ]
    },
    'Senegal': {
      code: 'SEN',
      flag: '🇸🇳',
      players: [
        { number: 1, name: 'Seny Dieng', position: 'GR', rating: 79 },
        { number: 2, name: 'Formose Mendy', position: 'D', rating: 76 },
        { number: 3, name: 'Kalidou Koulibaly', position: 'D', rating: 84 },
        { number: 4, name: 'Pape Abou Cissé', position: 'D', rating: 77 },
        { number: 5, name: 'Idrissa Gueye', position: 'M', rating: 80 },
        { number: 6, name: 'Nampalys Mendy', position: 'M', rating: 76 },
        { number: 7, name: 'Nicolas Jackson', position: 'A', rating: 78 },
        { number: 8, name: 'Cheikhou Kouyaté', position: 'M', rating: 78 },
        { number: 9, name: 'Boulaye Dia', position: 'A', rating: 79 },
        { number: 10, name: 'Moussa N\'Diaye', position: 'A', rating: 75 },
        { number: 11, name: 'Pathé Ciss', position: 'M', rating: 74 },
        { number: 12, name: 'Édouard Mendy', position: 'GR', rating: 82 },
        { number: 13, name: 'Fodé Ballo-Touré', position: 'D', rating: 75 },
        { number: 14, name: 'Iliman Ndiaye', position: 'A', rating: 77 },
        { number: 15, name: 'Ismail Jakobs', position: 'D', rating: 75 },
        { number: 16, name: 'Krépin Diatta', position: 'M', rating: 77 },
        { number: 17, name: 'Pape Matar Sarr', position: 'M', rating: 76 },
        { number: 18, name: 'Ismaïla Sarr', position: 'A', rating: 80 },
        { number: 19, name: 'Famara Diédhiou', position: 'A', rating: 76 },
        { number: 20, name: 'Bamba Dieng', position: 'A', rating: 75 },
        { number: 21, name: 'Youssouf Sabaly', position: 'D', rating: 77 },
        { number: 22, name: 'Abdou Diallo', position: 'D', rating: 78 },
        { number: 23, name: 'Alfred Gomis', position: 'GR', rating: 76 },
        { number: 24, name: 'Moustapha Name', position: 'M', rating: 73 },
        { number: 25, name: 'Mamadou Loum', position: 'M', rating: 72 },
        { number: 26, name: 'Pape Gueye', position: 'M', rating: 74 }
      ]
    },
    'Equador': {
      code: 'ECU',
      flag: '🇪🇨',
      players: [
        { number: 1, name: 'Hernán Galíndez', position: 'GR', rating: 76 },
        { number: 2, name: 'Félix Torres', position: 'D', rating: 77 },
        { number: 3, name: 'Piero Hincapié', position: 'D', rating: 79 },
        { number: 4, name: 'Robert Arboleda', position: 'D', rating: 78 },
        { number: 5, name: 'José Cifuentes', position: 'M', rating: 75 },
        { number: 6, name: 'Willian Pacho', position: 'D', rating: 76 },
        { number: 7, name: 'Pervis Estupiñán', position: 'D', rating: 77 },
        { number: 8, name: 'Carlos Gruezo', position: 'M', rating: 76 },
        { number: 9, name: 'Ayrton Preciado', position: 'M', rating: 74 },
        { number: 10, name: 'Romario Ibarra', position: 'M', rating: 75 },
        { number: 11, name: 'Michael Estrada', position: 'A', rating: 76 },
        { number: 12, name: 'Moisés Ramírez', position: 'GR', rating: 73 },
        { number: 13, name: 'Enner Valencia', position: 'A', rating: 80 },
        { number: 14, name: 'Xavier Arreaga', position: 'D', rating: 75 },
        { number: 15, name: 'Ángel Mena', position: 'M', rating: 74 },
        { number: 16, name: 'Jeremy Sarmiento', position: 'M', rating: 76 },
        { number: 17, name: 'Ángelo Preciado', position: 'D', rating: 74 },
        { number: 18, name: 'Diego Palacios', position: 'D', rating: 75 },
        { number: 19, name: 'Gonzalo Plata', position: 'M', rating: 76 },
        { number: 20, name: 'Jhegson Méndez', position: 'M', rating: 73 },
        { number: 21, name: 'Alan Franco', position: 'M', rating: 72 },
        { number: 22, name: 'Alexander Domínguez', position: 'GR', rating: 75 },
        { number: 23, name: 'Moisés Caicedo', position: 'M', rating: 78 },
        { number: 24, name: 'Djorkaeff Reasco', position: 'A', rating: 71 },
        { number: 25, name: 'Jackson Porozo', position: 'D', rating: 73 },
        { number: 26, name: 'Kevin Rodríguez', position: 'A', rating: 70 }
      ]
    },
    'Catar': {
      code: 'QAT',
      flag: '🇶🇦',
      players: [
        { number: 1, name: 'Saad Al Sheeb', position: 'GR', rating: 76 },
        { number: 2, name: 'Ró-Ró', position: 'D', rating: 75 },
        { number: 3, name: 'Abdelkarim Hassan', position: 'D', rating: 76 },
        { number: 4, name: 'Mohammed Waad', position: 'M', rating: 73 },
        { number: 5, name: 'Tarek Salman', position: 'D', rating: 74 },
        { number: 6, name: 'Abdulaziz Hatem', position: 'M', rating: 75 },
        { number: 7, name: 'Ahmed Alaaeldin', position: 'A', rating: 72 },
        { number: 8, name: 'Ali Assadalla', position: 'M', rating: 74 },
        { number: 9, name: 'Mohammed Muntari', position: 'A', rating: 73 },
        { number: 10, name: 'Hassan Al-Haydos', position: 'A', rating: 77 },
        { number: 11, name: 'Akram Afif', position: 'A', rating: 78 },
        { number: 12, name: 'Karim Boudiaf', position: 'M', rating: 74 },
        { number: 13, name: 'Musab Kheder', position: 'D', rating: 73 },
        { number: 14, name: 'Homam Ahmed', position: 'D', rating: 72 },
        { number: 15, name: 'Bassam Al-Rawi', position: 'D', rating: 73 },
        { number: 16, name: 'Boualem Khoukhi', position: 'D', rating: 75 },
        { number: 17, name: 'Ismaeel Mohammad', position: 'M', rating: 72 },
        { number: 18, name: 'Khalid Muneer', position: 'A', rating: 70 },
        { number: 19, name: 'Almoez Ali', position: 'A', rating: 76 },
        { number: 20, name: 'Salem Al-Hajri', position: 'M', rating: 71 },
        { number: 21, name: 'Yousef Hassan', position: 'GR', rating: 72 },
        { number: 22, name: 'Meshaal Barsham', position: 'GR', rating: 74 },
        { number: 23, name: 'Assim Madibo', position: 'M', rating: 71 },
        { number: 24, name: 'Naif Al-Hadhrami', position: 'A', rating: 69 },
        { number: 25, name: 'Jassem Gaber', position: 'D', rating: 70 },
        { number: 26, name: 'Mostafa Tarek', position: 'M', rating: 70 }
      ]
    },
    'EUA': {
      code: 'USA',
      flag: '🇺🇸',
      players: [
        { number: 1, name: 'Matt Turner', position: 'GR', rating: 77 },
        { number: 2, name: 'Sergiño Dest', position: 'D', rating: 78 },
        { number: 3, name: 'Joe Scally', position: 'D', rating: 77 },
        { number: 4, name: 'Walker Zimmerman', position: 'D', rating: 76 },
        { number: 5, name: 'Antonee Robinson', position: 'D', rating: 78 },
        { number: 6, name: 'Tyler Adams', position: 'M', rating: 78 },
        { number: 7, name: 'Weston McKennie', position: 'M', rating: 79 },
        { number: 8, name: 'Yunus Musah', position: 'M', rating: 77 },
        { number: 9, name: 'Christian Pulisic', position: 'A', rating: 83 },
        { number: 10, name: 'Gio Reyna', position: 'A', rating: 80 },
        { number: 11, name: 'Folarin Balogun', position: 'A', rating: 78 },
        { number: 12, name: 'Ethan Horvath', position: 'GR', rating: 75 },
        { number: 13, name: 'Joe Corona', position: 'D', rating: 74 },
        { number: 14, name: 'Luca de la Torre', position: 'M', rating: 75 },
        { number: 15, name: 'Kellyn Acosta', position: 'M', rating: 75 },
        { number: 16, name: 'Antonee Robinson', position: 'D', rating: 77 },
        { number: 17, name: 'Jalen Neal', position: 'D', rating: 73 },
        { number: 18, name: 'Romain Saïss', position: 'D', rating: 76 },
        { number: 19, name: 'Daryl Dike', position: 'A', rating: 76 },
        { number: 20, name: 'Malik Tillman', position: 'M', rating: 75 },
        { number: 21, name: 'Joe Scally', position: 'D', rating: 77 },
        { number: 22, name: 'Zack Steffen', position: 'GR', rating: 74 },
        { number: 23, name: 'Shaq Moore', position: 'D', rating: 74 },
        { number: 24, name: 'Gio Reyna', position: 'A', rating: 80 },
        { number: 25, name: 'Sergiño Dest', position: 'D', rating: 78 },
        { number: 26, name: 'Gregg Berhalter', position: 'M', rating: 72 }
      ]
    },
    'Irã': {
      code: 'IRN',
      flag: '🇮🇷',
      players: [
        { number: 1, name: 'Alireza Beiranvand', position: 'GR', rating: 76 },
        { number: 2, name: 'Ehsan Hajsafi', position: 'D', rating: 75 },
        { number: 3, name: 'Ramin Rezaeian', position: 'D', rating: 74 },
        { number: 4, name: 'Majid Hosseini', position: 'D', rating: 75 },
        { number: 5, name: 'Milad Mohammadi', position: 'D', rating: 74 },
        { number: 6, name: 'Omid Ebrahimi', position: 'M', rating: 73 },
        { number: 7, name: 'Mehdi Torabi', position: 'M', rating: 72 },
        { number: 8, name: 'Saeid Ezatolahi', position: 'M', rating: 73 },
        { number: 9, name: 'Karim Ansarifard', position: 'A', rating: 75 },
        { number: 10, name: 'Sardar Azmoun', position: 'A', rating: 78 },
        { number: 11, name: 'Alireza Jahanbakhsh', position: 'A', rating: 77 },
        { number: 12, name: 'Amir Abedzadeh', position: 'GR', rating: 74 },
        { number: 13, name: 'Reza Cheshmi', position: 'D', rating: 73 },
        { number: 14, name: 'Vahid Amiri', position: 'M', rating: 72 },
        { number: 15, name: 'Saman Ghoddos', position: 'M', rating: 74 },
        { number: 16, name: 'Borna Barisic', position: 'D', rating: 76 },
        { number: 17, name: 'Shahriar Moghanlou', position: 'A', rating: 70 },
        { number: 18, name: 'Payam Niazmand', position: 'M', rating: 71 },
        { number: 19, name: 'Mehdi Taremi', position: 'A', rating: 76 },
        { number: 20, name: 'Morteza Pouraliganji', position: 'D', rating: 72 },
        { number: 21, name: 'Mohammad Mohebi', position: 'M', rating: 70 },
        { number: 22, name: 'Hossein Hosseini', position: 'GR', rating: 72 },
        { number: 23, name: 'Ramin Rezaeian', position: 'D', rating: 74 },
        { number: 24, name: 'Arash Rezavand', position: 'D', rating: 71 },
        { number: 25, name: 'Abolfazl Jalali', position: 'A', rating: 71 },
        { number: 26, name: 'Milad Mohammadi', position: 'D', rating: 74 }
      ]
    },
    'Gales': {
      code: 'WAL',
      flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
      players: [
        { number: 1, name: 'Wayne Hennessey', position: 'GR', rating: 76 },
        { number: 2, name: 'Ben Davies', position: 'D', rating: 77 },
        { number: 3, name: 'Chris Mepham', position: 'D', rating: 75 },
        { number: 4, name: 'Joe Rodon', position: 'D', rating: 78 },
        { number: 5, name: 'Ethan Ampadu', position: 'D', rating: 76 },
        { number: 6, name: 'Aaron Ramsey', position: 'M', rating: 77 },
        { number: 7, name: 'Joe Allen', position: 'M', rating: 76 },
        { number: 8, name: 'Gareth Bale', position: 'A', rating: 84 },
        { number: 9, name: 'Kieffer Moore', position: 'A', rating: 75 },
        { number: 10, name: 'Daniel James', position: 'A', rating: 77 },
        { number: 11, name: 'Harry Wilson', position: 'A', rating: 76 },
        { number: 12, name: 'Danny Ward', position: 'GR', rating: 74 },
        { number: 13, name: 'Connor Roberts', position: 'D', rating: 75 },
        { number: 14, name: 'Neco Williams', position: 'D', rating: 76 },
        { number: 15, name: 'Sorba Thomas', position: 'D', rating: 74 },
        { number: 16, name: 'Jonny Williams', position: 'M', rating: 74 },
        { number: 17, name: 'Brennan Johnson', position: 'A', rating: 77 },
        { number: 18, name: 'Tyler Roberts', position: 'A', rating: 73 },
        { number: 19, name: 'Wes Burns', position: 'A', rating: 74 },
        { number: 20, name: 'David Brooks', position: 'M', rating: 76 },
        { number: 21, name: 'Rhys Norrington-Davies', position: 'D', rating: 73 },
        { number: 22, name: 'Adam Davies', position: 'GR', rating: 73 },
        { number: 23, name: 'Andy King', position: 'M', rating: 73 },
        { number: 24, name: 'Rubin Colwill', position: 'M', rating: 74 },
        { number: 25, name: 'Liam Cullen', position: 'A', rating: 72 },
        { number: 26, name: 'Mark Harris', position: 'A', rating: 71 }
      ]
    },
    'Austrália': {
      code: 'AUS',
      flag: '🇦🇺',
      players: [
        { number: 1, name: 'Mathew Ryan', position: 'GR', rating: 77 },
        { number: 2, name: 'Fran Karacic', position: 'D', rating: 74 },
        { number: 3, name: 'Kye Rowles', position: 'D', rating: 75 },
        { number: 4, name: 'Milos Degenek', position: 'D', rating: 74 },
        { number: 5, name: 'Aziz Behich', position: 'D', rating: 75 },
        { number: 6, name: 'Aaron Mooy', position: 'M', rating: 76 },
        { number: 7, name: 'Jackson Irvine', position: 'M', rating: 75 },
        { number: 8, name: 'Ajdin Hrustić', position: 'M', rating: 74 },
        { number: 9, name: 'Mitchell Duke', position: 'A', rating: 74 },
        { number: 10, name: 'Awer Mabil', position: 'A', rating: 75 },
        { number: 11, name: 'Martin Boyle', position: 'A', rating: 76 },
        { number: 12, name: 'Andrew Redmayne', position: 'GR', rating: 73 },
        { number: 13, name: 'Harry Souttar', position: 'D', rating: 76 },
        { number: 14, name: 'Alexis Mac Allister', position: 'M', rating: 77 },
        { number: 15, name: 'Denis Genreau', position: 'M', rating: 72 },
        { number: 16, name: 'Keanu Baccus', position: 'M', rating: 73 },
        { number: 17, name: 'Craig Goodwin', position: 'A', rating: 74 },
        { number: 18, name: 'Giancarlo Prestia', position: 'M', rating: 72 },
        { number: 19, name: 'Marco Tilio', position: 'A', rating: 73 },
        { number: 20, name: 'Nishan Burkart', position: 'D', rating: 71 },
        { number: 21, name: 'Connor Chapman', position: 'D', rating: 70 },
        { number: 22, name: 'Joe Gauci', position: 'GR', rating: 72 },
        { number: 23, name: 'Callum Timmins', position: 'D', rating: 70 },
        { number: 24, name: 'Jason Cummings', position: 'A', rating: 72 },
        { number: 25, name: 'Kristian Popovic', position: 'D', rating: 71 },
        { number: 26, name: 'Lachlan Rose', position: 'M', rating: 70 }
      ]
    },
    'Tunísia': {
      code: 'TUN',
      flag: '🇹🇳',
      players: [
        { number: 1, name: 'Aymen Dahmen', position: 'GR', rating: 74 },
        { number: 2, name: 'Ali Maaloul', position: 'D', rating: 74 },
        { number: 3, name: 'Ramy Bensebaini', position: 'D', rating: 75 },
        { number: 4, name: 'Nabil Tarek', position: 'D', rating: 73 },
        { number: 5, name: 'Yassine Meriah', position: 'D', rating: 74 },
        { number: 6, name: 'Aïssa Laidouni', position: 'M', rating: 73 },
        { number: 7, name: 'Ellyes Skhiri', position: 'M', rating: 75 },
        { number: 8, name: 'Mohamed Amine Ben Amor', position: 'M', rating: 72 },
        { number: 9, name: 'Issam Jebali', position: 'A', rating: 73 },
        { number: 10, name: 'Youssef Msakni', position: 'A', rating: 74 },
        { number: 11, name: 'Naïm Sliti', position: 'A', rating: 72 },
        { number: 12, name: 'Farouk Ben Mustapha', position: 'GR', rating: 72 },
        { number: 13, name: 'Wajdi Kechrida', position: 'D', rating: 72 },
        { number: 14, name: 'Hannibal Mejbri', position: 'M', rating: 75 },
        { number: 15, name: 'Ghislain Konan', position: 'M', rating: 71 },
        { number: 16, name: 'Mohamed Drager', position: 'D', rating: 73 },
        { number: 17, name: 'Taha Yassine Khenissi', position: 'A', rating: 72 },
        { number: 18, name: 'Seifeddine Jaziri', position: 'A', rating: 71 },
        { number: 19, name: 'Oussama Haddadi', position: 'A', rating: 70 },
        { number: 20, name: 'Bilel Ifa', position: 'M', rating: 70 },
        { number: 21, name: 'Montassar Talbi', position: 'D', rating: 72 },
        { number: 22, name: 'Mouez Hassen', position: 'GR', rating: 71 },
        { number: 23, name: 'Karim Aouadhi', position: 'D', rating: 70 },
        { number: 24, name: 'Ferjani Sassi', position: 'M', rating: 71 },
        { number: 25, name: 'Hamza Rafia', position: 'M', rating: 70 },
        { number: 26, name: 'Mohamed Abdelmonem', position: 'D', rating: 69 }
      ]
    },
    'Costa Rica': {
      code: 'CRC',
      flag: '🇨🇷',
      players: [
        { number: 1, name: 'Keylor Navas', position: 'GR', rating: 83 },
        { number: 2, name: 'Juan Pablo Vargas', position: 'D', rating: 75 },
        { number: 3, name: 'Óscar Duarte', position: 'D', rating: 76 },
        { number: 4, name: 'Francisco Calvo', position: 'D', rating: 74 },
        { number: 5, name: 'Rónald Matarrita', position: 'D', rating: 75 },
        { number: 6, name: 'Yeltsin Tejeda', position: 'M', rating: 72 },
        { number: 7, name: 'Celso Borges', position: 'M', rating: 74 },
        { number: 8, name: 'Jewison Bennette', position: 'M', rating: 73 },
        { number: 9, name: 'Álvaro Zamora', position: 'A', rating: 72 },
        { number: 10, name: 'Bryan Ruiz', position: 'A', rating: 75 },
        { number: 11, name: 'Anthony Contreras', position: 'A', rating: 71 },
        { number: 12, name: 'Esteban Alvarado', position: 'GR', rating: 72 },
        { number: 13, name: 'Carlos Martínez', position: 'D', rating: 73 },
        { number: 14, name: 'Ariel Rodríguez', position: 'M', rating: 71 },
        { number: 15, name: 'Rándall Leal', position: 'M', rating: 72 },
        { number: 16, name: 'Aarón Cruz', position: 'M', rating: 70 },
        { number: 17, name: 'Gerson Torres', position: 'A', rating: 71 },
        { number: 18, name: 'Mauricio Montero', position: 'A', rating: 70 },
        { number: 19, name: 'Kendall Waston', position: 'D', rating: 74 },
        { number: 20, name: 'Jefry Valverde', position: 'D', rating: 71 },
        { number: 21, name: 'Leonel Moreira', position: 'GR', rating: 71 },
        { number: 22, name: 'Carvajal', position: 'D', rating: 72 },
        { number: 23, name: 'Óscar Granados', position: 'M', rating: 70 },
        { number: 24, name: 'Ricky Sandoval', position: 'M', rating: 70 },
        { number: 25, name: 'Rubilio Castillo', position: 'A', rating: 70 },
        { number: 26, name: 'Douglas López', position: 'D', rating: 70 }
      ]
    },
    'Camarões': {
      code: 'CMR',
      flag: '🇨🇲',
      players: [
        { number: 1, name: 'André Onana', position: 'GR', rating: 81 },
        { number: 2, name: 'Enzo Ebosse', position: 'D', rating: 74 },
        { number: 3, name: 'Jemerson', position: 'D', rating: 75 },
        { number: 4, name: 'Nouhou Tolo', position: 'D', rating: 74 },
        { number: 5, name: 'Achille Webo', position: 'D', rating: 73 },
        { number: 6, name: 'Samuel Oum Gouet', position: 'M', rating: 72 },
        { number: 7, name: 'Pierre Kunde', position: 'M', rating: 73 },
        { number: 8, name: 'Olivier Ntcham', position: 'M', rating: 74 },
        { number: 9, name: 'Stéphane Bahoken', position: 'A', rating: 73 },
        { number: 10, name: 'Vincent Aboubakar', position: 'A', rating: 76 },
        { number: 11, name: 'Christian Bassogog', position: 'A', rating: 72 },
        { number: 12, name: 'Fabrice Ondoa', position: 'GR', rating: 71 },
        { number: 13, name: 'Fai Fai Bobo', position: 'D', rating: 72 },
        { number: 14, name: 'Gaël Ondoua', position: 'M', rating: 71 },
        { number: 15, name: 'Léandre Tawamba', position: 'M', rating: 70 },
        { number: 16, name: 'Léon Osman', position: 'M', rating: 71 },
        { number: 17, name: 'Choupo-Moting', position: 'A', rating: 75 },
        { number: 18, name: 'Maxim Choupo-Moting', position: 'A', rating: 75 },
        { number: 19, name: 'Moumi Ngamaleu', position: 'D', rating: 72 },
        { number: 20, name: 'Ambroise Oyongo', position: 'D', rating: 71 },
        { number: 21, name: 'Yaya Banana', position: 'M', rating: 70 },
        { number: 22, name: 'Simon Ngapandouetnbu', position: 'GR', rating: 70 },
        { number: 23, name: 'Castellanos', position: 'D', rating: 70 },
        { number: 24, name: 'Zambo Anguissa', position: 'M', rating: 73 },
        { number: 25, name: 'Toko Ekambi', position: 'A', rating: 74 },
        { number: 26, name: 'Ngamaleu', position: 'D', rating: 71 }
      ]
    },
    'Gana': {
      code: 'GHA',
      flag: '🇬🇭',
      players: [
        { number: 1, name: 'Jojo Wollacott', position: 'GR', rating: 74 },
        { number: 2, name: 'Seidu Waris', position: 'D', rating: 72 },
        { number: 3, name: 'Daniel Amartey', position: 'D', rating: 74 },
        { number: 4, name: 'Jeremiah Attamah', position: 'D', rating: 71 },
        { number: 5, name: 'Andy Yiadom', position: 'D', rating: 73 },
        { number: 6, name: 'Thomas Partey', position: 'M', rating: 80 },
        { number: 7, name: 'Mubarak Wakaso', position: 'M', rating: 73 },
        { number: 8, name: 'Mohammed Kudus', position: 'M', rating: 77 },
        { number: 9, name: 'Osman Bukari', position: 'A', rating: 72 },
        { number: 10, name: 'André Ayew', position: 'A', rating: 75 },
        { number: 11, name: 'Inaki Williams', position: 'A', rating: 76 },
        { number: 12, name: 'Richard Ofori', position: 'GR', rating: 72 },
        { number: 13, name: 'Baba Rahman', position: 'D', rating: 73 },
        { number: 14, name: 'Elisha Owusu', position: 'M', rating: 71 },
        { number: 15, name: 'Semenyo', position: 'M', rating: 72 },
        { number: 16, name: 'Lamptey', position: 'D', rating: 74 },
        { number: 17, name: 'Kyereh', position: 'M', rating: 72 },
        { number: 18, name: 'Paintsil', position: 'A', rating: 73 },
        { number: 19, name: 'Owusu-Koramoah', position: 'D', rating: 75 },
        { number: 20, name: 'Djiku', position: 'D', rating: 73 },
        { number: 21, name: 'Mensah', position: 'D', rating: 72 },
        { number: 22, name: 'Ati-Zigi', position: 'GR', rating: 71 },
        { number: 23, name: 'Castillo', position: 'D', rating: 70 },
        { number: 24, name: 'Sulemana', position: 'M', rating: 74 },
        { number: 25, name: 'Asamoah', position: 'A', rating: 71 },
        { number: 26, name: 'Yeboah', position: 'A', rating: 70 }
      ]
    },
    'Suíça': {
      code: 'SUI',
      flag: '🇨🇭',
      players: [
        { number: 1, name: 'Yann Sommer', position: 'GR', rating: 83 },
        { number: 2, name: 'Silvan Widmer', position: 'D', rating: 77 },
        { number: 3, name: 'Manuel Akanji', position: 'D', rating: 81 },
        { number: 4, name: 'Fabian Schär', position: 'D', rating: 79 },
        { number: 5, name: 'Remo Freuler', position: 'M', rating: 77 },
        { number: 6, name: 'Granit Xhaka', position: 'M', rating: 81 },
        { number: 7, name: 'Xherdan Shaqiri', position: 'M', rating: 80 },
        { number: 8, name: 'Denis Zakaria', position: 'M', rating: 78 },
        { number: 9, name: 'Breel Embolo', position: 'A', rating: 78 },
        { number: 10, name: 'Haris Seferović', position: 'A', rating: 76 },
        { number: 11, name: 'Ruben Vargas', position: 'A', rating: 76 },
        { number: 12, name: 'Gregor Kobel', position: 'GR', rating: 80 },
        { number: 13, name: 'Nico Elvedi', position: 'D', rating: 78 },
        { number: 14, name: 'Eray Cömert', position: 'D', rating: 76 },
        { number: 15, name: 'Edimilson Fernandes', position: 'M', rating: 74 },
        { number: 16, name: 'Djibril Sow', position: 'M', rating: 76 },
        { number: 17, name: 'Renato Steffen', position: 'A', rating: 74 },
        { number: 18, name: 'Noah Okafor', position: 'A', rating: 76 },
        { number: 19, name: 'Loïc Meillard', position: 'M', rating: 75 },
        { number: 20, name: 'Jérôme Onguéné', position: 'D', rating: 74 },
        { number: 21, name: 'Becir Omeragić', position: 'D', rating: 73 },
        { number: 22, name: 'Jonas Omlin', position: 'GR', rating: 76 },
        { number: 23, name: 'Cédric Zesiger', position: 'D', rating: 72 },
        { number: 24, name: 'Leonidas Stergiou', position: 'D', rating: 72 },
        { number: 25, name: 'Dereck Kutesa', position: 'A', rating: 71 },
        { number: 26, name: 'Andi Zeqiri', position: 'A', rating: 72 }
      ]
    },
    'Dinamarca': {
      code: 'DEN',
      flag: '🇩🇰',
      players: [
        { number: 1, name: 'Kasper Schmeichel', position: 'GR', rating: 82 },
        { number: 2, name: 'Jens Stryger Larsen', position: 'D', rating: 76 },
        { number: 3, name: 'Jannik Vestergaard', position: 'D', rating: 78 },
        { number: 4, name: 'Andreas Christensen', position: 'D', rating: 79 },
        { number: 5, name: 'Riza Durmisi', position: 'D', rating: 74 },
        { number: 6, name: 'Thomas Delaney', position: 'M', rating: 77 },
        { number: 7, name: 'Pierre-Emile Højbjerg', position: 'M', rating: 79 },
        { number: 8, name: 'Christian Eriksen', position: 'M', rating: 84 },
        { number: 9, name: 'Yussuf Poulsen', position: 'A', rating: 77 },
        { number: 10, name: 'Kasper Dolberg', position: 'A', rating: 76 },
        { number: 11, name: 'Andreas Skov Olsen', position: 'A', rating: 75 },
        { number: 12, name: 'Frederik Rønow', position: 'GR', rating: 74 },
        { number: 13, name: 'Simon Kjær', position: 'D', rating: 78 },
        { number: 14, name: 'Morten Hjulmand', position: 'M', rating: 76 },
        { number: 15, name: 'Mathias Jensen', position: 'M', rating: 75 },
        { number: 16, name: 'Rasmus Nissen Kristensen', position: 'D', rating: 75 },
        { number: 17, name: 'Jens Andersen', position: 'A', rating: 73 },
        { number: 18, name: 'Mikkel Damsgaard', position: 'M', rating: 77 },
        { number: 19, name: 'Jesper Lindström', position: 'A', rating: 75 },
        { number: 20, name: 'Sander Tielemans', position: 'M', rating: 74 },
        { number: 21, name: 'Nicolai Boilesen', position: 'D', rating: 73 },
        { number: 22, name: 'Rikke Sevecus', position: 'GR', rating: 72 },
        { number: 23, name: 'Joakim Mæhle', position: 'D', rating: 76 },
        { number: 24, name: 'Jens Andersen', position: 'A', rating: 73 },
        { number: 25, name: 'Lukas Lerager', position: 'M', rating: 74 },
        { number: 26, name: 'Kaan Ayhan', position: 'D', rating: 75 }
      ]
    }
  }
};

// Função para sortear grupos aleatoriamente
function generateRandomGroups(teams, numGroups = 8, teamsPerGroup = 4) {
  const teamNames = Object.keys(teams);
  const shuffled = [...teamNames].sort(() => Math.random() - 0.5);
  const groups = {};
  const groupLetters = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'];
  
  for (let i = 0; i < numGroups; i++) {
    groups[groupLetters[i]] = shuffled.slice(i * teamsPerGroup, (i + 1) * teamsPerGroup);
  }
  
  return groups;
}

// Gerar grupos aleatórios
WORLD_CUP_DATA.groups = generateRandomGroups(WORLD_CUP_DATA.allTeams);
